### ISSUE TITLE
Dismissing combobox with esc

### ISSUE THREAD

**Issue by JonnyTech** [graemeg/fpGUI#50] opened 2016-08-17 08:35 UTC
If a combobox is in a dropdown state (with its contents showing), pressing the escape key on the keyboard to dismiss it causes the program to generate an error message:

An unexpected error occurred.
ess violation
OK

**Comment by JonnyTech** [comment] 2016-08-17 08:40
This only seems to affect the develop branch

**Comment by andrewd207** [comment] 2016-08-18 01:33
Hi, I'm looking into this. It's a weird problem. The msg.Dest is apparently invalid indicating that the dest was freed but destroy hasn't been called afaict.

**Comment by andrewd207** [comment] 2016-08-18 02:11
Fixed in ee1feddf013dea44517d0dcdaef9ef85742a2c8a. A message was queued for the native window of the popup which gets destroyed when .Close is called. Now the message is removed from the queue if it exists before the window gets destroyed.

**Closed as completed by andrewd207** 2016-08-18 02:11 UTC

**Comment by andrewd207** [comment] 2016-08-18 02:37
Just fixed the same bug for TfpgEditCombo as well.

**Comment by graemeg** [comment] 2016-08-18 10:59
Many thanks for resolving this Andrew. I couldn't reproduce the error on my development system (FreeBSD).
Looking at the change made, I wonder if the consumed variable didn't play a part in the problem. It was never checked and never changed. eg: Checking the KeyCode before the inherited call - if KeyCode = keyEscape then set consumed := True, maybe not even call inherited then. Just thinking out loudly - but like I said, I couldn't reproduce the issue to start with.

**Comment by andrewd207** [comment] 2016-08-18 23:08
No, at least in the x11 implementation the keypress message has a keychar message immediately queued after. The combo responds to the keypress which destroys the native window that has a message about to arrive.

**Comment by graemeg** [comment] 2016-08-18 23:58
I think there are other Combox -type widgets that will also be affected by this (eg: Calendar Combo, possible popup menus too etc). They all use the "popup window", so wouldn't it maybe be a better idea to simply clear the message queue in the destructor of the popup window class. Or the destructor of the Native Window class. That should fix all widgets using popup window?

**Comment by andrewd207** [comment] 2016-08-19 00:11
I just tested and you are right. Esc with menu's crashes and probably other things as well. I will change this later tonight and remove the other fixes I added.

**Comment by JonnyTech** [comment] 2016-09-04 21:47
Sorry to reopen this - the same error is reproducible in the fontselect demo.
With TfpgFontSelectDialog press ESC to bring up the same error message.

**Comment by graemeg** [comment] 2016-09-05 23:59
As I mentioned in the newsgroup, this should now be resolved too. Thanks again for bringing this to my attention.

**Comment by JonnyTech** [comment] 2016-09-06 05:50
Thanks for the speedy fix.
