### ISSUE TITLE
examples/combobox : unresponsive and eat 25 % of cpu time

### ISSUE THREAD

**Issue by saulery** [graemeg/fpGUI#68] opened 2017-11-04 19:25 UTC
Hello Graeme,

On windows, when I launch a combobox example freshly compiled I can make it freeze with the following steps :
1. Click on "Add 10 items" button
2. Click on the right button of the static combobox

The combobox is opened and the windows freeze immediately (no interaction possible, no move) and the combobox.exe process use constantly 25 % of the cpu time. The memory don't grow.

Have you an infinite loop somewhere?
![2017-11-04 20_08_22-c__devel_fpgui - astrogrep](https://user-images.githubusercontent.com/10128284/32408737-4ec1a6e6-c19e-11e7-9acd-6925e92fef86.png)
![2017_11_04_20_07_06_graemeg_fpgui_fpgui_toolkit_is_a_cross_platform_gui_toolkit_using_free_pascal](https://user-images.githubusercontent.com/10128284/32408738-4eeba20c-c19e-11e7-87e6-30ef88d35a7d.png)

Regards,

**Comment by saulery** [comment] 2017-11-04 22:41
Seem error with maximus IDE, but in that case I have just opened it ant it freezes. I use a x86_64-win64 target, maybe you have never tested this environment.

![2017-11-04_maximus_freeze](https://user-images.githubusercontent.com/10128284/32410118-6f61b916-c1b9-11e7-9265-609c06cc965f.png)

**Comment by graemeg** [comment] 2017-11-05 09:39
Thanks for all the testing. Yes, the new "develop" branch changes (alien_windows and aggpas_canvas) has not really been tested under Windows yet. So I expect many more issues there than under Linux or FreeBSD. My thinking was to first fix Linux and FreeBSD support, then move to Windows.

**Comment by saulery** [comment] 2017-11-05 14:26
If I want to test on Linux, I have to setup a new computer. I have what it takes but it will be for a little later.Can I test in Windows before and will you look at the bugs later? Has anyone ever tested on OpenBSD?

**Comment by graemeg** [comment] 2017-11-05 17:50
You are welcome to keep testing under Windows, because it will be useful to have a list of issue to tackle when I get to Windows development of the **develop** branch. Actually I've been thinking about it, and I think it is worth testing and fixing under all platforms at the same time. I have them all set up here, so it is no effort for me.

As for OpenBSD.... I haven't tested under that platform, but my main development system is FreeBSD 10.3 and where I do 99% of all my development work. I don't really know what or how much difference there are between FreeBSD and OpenBSD.

Please note that the platform instability is only in the **develop** branch. The **maint** branch is stable and very well tested under FreeBSD, Linux, Windows, Solaris, ARM Linux and Windows CE.

**Comment by saulery** [comment] 2017-11-06 23:37
Ok. I will test on windows. I intend to use fpGUI maint branch. It's just more useful to try and contribute against the dev branch.

**Comment by mhekeler** [comment] 2017-11-14 12:50
For the records:
I am using fpgui on `x86_64-openbsd` and never run in trouble. 
Examples runs fine and my own code I develop crossplattform on linux, win and openbsd.

**Comment by graemeg** [comment] 2017-11-14 20:47
Thank you Michael for your feedback. It seem to be a Windows only issue, as I don't have that problem under FreeBSD or Linux either. I am looking at this issue now under Win7 and Win10.

**Comment by graemeg** [comment] 2017-11-15 00:28
Thank you Michael for your feedback. It seem to be a Windows only issue, as I don't have that problem under FreeBSD or Linux either. I am looking at this issue now under Win7 and Win10.

**Comment by saulery** [comment] 2017-12-07 01:07
Thanks you Michael. It's to know that fpGUI and FPC work on OpenBSD.

**Comment by nelinnemann** [comment] 2018-08-25 06:30
Just to chime in, found same bug with Win10 X86_64, FPC 3.0.5, fpgui develop branch 25-08-2018.
If the combobox is smaller than the number of items it hangs, if the items are larger than content then no problem. Maybe it is related to the scrollbar.

![comboboxbug](https://user-images.githubusercontent.com/1086314/44615708-14329500-a841-11e8-93e4-b2f944b54815.gif)

**Comment by graemeg** [comment] 2018-11-01 20:00
This issue should now be fixed since commit 1a8548f5c0. I'll do another round of testing before I close this issue.

**Comment by graemeg** [comment] 2018-11-05 09:15
My testing confirmed that this bug has been resolved.

**Closed as completed by graemeg** 2018-11-05 09:15 UTC
