### ISSUE TITLE
About About-fpGUI-dialog.

### ISSUE THREAD

**Issue by fredvs** [graemeg/fpGUI#55] opened 2016-09-27 22:19 UTC
Hello Graeme.

In uidesigner, the logo of fpGUI in about-dialog is not draw completely with develop branch.

Here in attachment the logo centered.

[messagedialog.inc.zip](https://github.com/graemeg/fpGUI/files/496759/messagedialog.inc.zip)

OK, I stop to annoy you. ;-)

Fre;D

**Comment by graemeg** [comment] 2016-11-25 23:22
Centering the logo is simply ignoring the problem. I'm now busy looking into why the issue is happening in the first place. The issue got introduced with the alien-windows change, so maybe it is some issue with cliprect or update regions.

**Comment by fredvs** [comment] 2016-11-25 23:35
Hello Graeme.

Yes, there is problem with the cliprect.

A other way to reproduce it is with uidesigner.
On a form, create a panel and then add a button into the panel.
The button will cover outside the panel if button.left (or .top) is < 0.

**Comment by graemeg** [comment] 2016-11-26 00:01
Excellent example - now it is much easier to reproduce the issue. I'm current busy updating the unit tests included with fpGUI, just to double check the TfpgRect methods like UnionRect() etc to make sure they all
work as expect - because they had some implementation changes applied too.

**Comment by graemeg** [comment] 2016-11-27 11:33
> The button will cover outside the panel if button.left (or .top) is < 0.

That issue has been resolved - please get a 'develop' branch update. Unfortunately not all the cliprect issues are fixed yet - I'm working on that now.

**Comment by graemeg** [comment] 2016-12-10 23:47
This issue has been fixed in commit 88eafbd6. Please get an update, recompile uidesigner and retest.

**Closed as completed by graemeg** 2016-12-10 23:47 UTC
